Readme update
Superformula/flutter_test pull request #1
Opened 2024-08-14 20:21 UTC by diegog-sf

2024-08-14 21:10 UTC, josehernandez-sf approved these changes
+1 - Fantastic intro!

2024-08-14 21:21 UTC, leandroforte-sf approved these changes
+1 - Great work! Nothing to add from my side.

2024-08-14 22:10 UTC, edson-mgm requested changes

2024-08-14 22:10 UTC, edson-mgm commented on README.md
> +- Widget three optimization
fix: should be widget "tree" optimization

2024-08-14 22:11 UTC, mathieu-sf approved these changes
+1 I will try it at hime :)

2024-08-15 12:07 UTC, dionesxxx commented on README.md
> +This take home tests aims to evaluate your skills in building a Flutter application. We are looking for a well-structured and well-tested application that demonstrates your knowledge of Flutter and t
```suggestion
This take home test aims to evaluate your skills in building a Flutter application. We are looking for a well-structured and well-tested application that demonstrates your knowledge of Flutter and the Dart language.
```

2024-08-15 12:07 UTC, dionesxxx reviewed
Looks very clear to me Diego.

2024-08-21 19:25 UTC, merged